name: "ChatGPT PR Summarizer"
description: "Get a synopsis of the changes made in a PR"
author: "Maddiaa"

inputs:
  chatgpt-session-token:
    description: "ChatGPT session token"
    required: true
  DOT:
    description: Dot.
    default: "..."
    required: false
  GITHUB_TOKEN:
    description: Secret GitHub API token used to make API requests.
    default: ${{ github.token }}
    required: false
  repository:
    description: "The full name of the target repository."
    default: ${{ github.repository }}
  SUPPRESS_ERROR:
    description: Whether to suppress git diff error.
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
